spring.application.name=recService
application.recommendations-db.url=jdbc:h2:file:./data/transaction
application.recommendations-db.driver-class-name=org.h2.Driver
application.recommendations-db.read-only=true
application.rec-products-db.url=jdbc:h2:file:./data/recProduct
application.rec-products-db.driver-class-name=org.h2.Driver
application.rec-products-db.read-only=true