spring.application.name=recService
application.recommendations-db.url=jdbc:h2:file:./data/transaction
application.recommendations-db.driver-class-name=org.h2.Driver
application.recommendations-db.read-only=true